# Generated by Django 2.2.5 on 2020-03-11 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Real Estate', (('for rent', 'For Rent'), ('for sale', 'For Sale'), ('real estate services', 'Real Estate Services'))), ('Cars and Vehicles', (('cars and trucks', 'Cars And Trucks'), ('classic cars', 'Classic Cars'), ('vehicle parts', 'Vehicle Parts'), ('tires', 'Tires'), ('vehicle accessories', 'Vehicle Accessories'), ('motorcycles', 'Motorcycles'), ('atvs and snowmobiles', 'ATVs and Snowmobiles'), ('boats and watercraft', 'Boats and Watercraft'), ('rvs, campers, trailers', 'RVs, Campers and Trailers'), ('heavy equipment', 'Heavy Equipment'), ('other', 'other'))), ('Buy and Sell', (('arts and collectibles', 'Arts and Collectibles'), ('audio', 'Audio'), ('baby items', 'Baby Items'), ('bikes', 'Bikes'), ('books', 'Books'), ('business and industrial', 'Business and Industrial'), ('cameras and camcorders', 'Cameras and Camcorders'), ('cds, dvds and blu rays', 'CDs, DVDs, and Blu-Ray'), ('clothing', 'Clothing'), ('computers', 'Computers'), ('computer accessories', 'Computer Accessories'), ('electronics', 'Electronics'), ('free stuff', 'Free Stuff'), ('furniture', 'Furniture'), ('garage sales', 'Garage Sales'), ('health and special needs', 'Health and Special Needs'), ('hobbies and crafts', 'Hobbies and Crafts'), ('home appliances', 'Home Appliances'), ('home indoor', 'Home - Indoor'), ('home outdoor and garden', 'Home - Outdoor and Garden'), ('home renovation materials', 'Home Renovation Materials'), ('jewellery and watches', 'Jewellery and Watches'), ('phones', 'Phones'), ('sporting goods and exercise', 'Sporting Goods and Exercise'), ('tickers', 'Tickets'), ('tools', 'Tools'), ('toys and games', 'Toys and Games'), ('tvs and video', 'TVs and Video'), ('video games', 'Video Games and Consoles'), ('other', 'Other')))], max_length=50)),
                ('ad_type', models.CharField(choices=[('selling', 'I am selling'), ('buying', 'I am buying')], max_length=50)),
                ('for_sale_by', models.CharField(choices=[('owner', 'Owner'), ('business', 'Business')], max_length=50)),
                ('ad_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000)),
                ('images', models.ImageField(blank=True, upload_to='media/')),
                ('youtube_video_link', models.URLField()),
                ('website_url_link', models.URLField()),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('price_options', models.CharField(choices=[('listed price', 'Listed Price'), ('free', 'Free'), ('please contact', 'Please Contact'), ('swap or trade', 'Swap / Trade')], max_length=50)),
                ('phone_num', models.CharField(max_length=50)),
                ('email', models.EmailField(help_text='A valid email address, please', max_length=254)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
